# Build documentation
name: publish-prod

# Controls when the workflow will run
on: workflow_dispatch

jobs:

  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.101.0_Linux-64bit.deb
          
      - name: Build site
        run: |
          hugo --minify --config config-geekdoc.toml,ignore-total-config.toml

      - name: Move MD files to ugly URLs
        run: ./move_md_to_ugly_urls.sh

      - name: Deploy artifacts
        uses: nogsantos/scp-deploy@master
        with:
          src: ./public/*
          host: ${{ secrets.DOCS_SSH_HOST }}
          remote: ${{ secrets.DOCS_SSH_DIR }}
          user: ${{ secrets.DOCS_SSH_USER }}
          key: ${{ secrets.DOCS_SSH_KEY }}

